### ISSUE TITLE
Error with legend locations?

### ISSUE THREAD

**Issue by zfasnacht1013** [matplotlib/cheatsheets#51]
Think there may be an error in your cheatsheet. The legend locations seem to be different than those in the matplotlib documentation:

https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.legend.html#:~:text=matplotlib.pyplot.legend%20%C2%B6%20%20%20%20Location%20String%20,%20%203%20%207%20more%20rows%20

**Comment by timhoffm** [comment]
I suppose the numbers are only intended as a link between the position and the string given below.

While one can use integers as location codes, that use is discouraged. It's also not easy to remember as the numbers jump a bit because you first count the corners then the edges the the center. Therefore, I would not show the location codes.

Possible fixes:
- use lowercase letters on the inside (for the orange boxes)
- alternatively, directly write the string at the postition.

**Comment by rougier** [comment]
There's a pending PR to fix that that still needs to be merged. I'll check it.

**Comment by BirkoRuzicka** [comment]
I found this quite confusing and frustrating too. If the code allows me to write "loc = 2" then I would have hoped that this corresponds to the "2" in the orange box. But no. I spoke about this with some co-workers, who had the same issue with the cheat sheet. Please consider changing this. Thank you!

**Comment by rougier** [comment]
Actually it has been fixed with https://github.com/matplotlib/cheatsheets/pull/40 but it is not displayed yet. We now have an automated build that will upload the cheatsheets at the proper place.

**Comment by jimustafa** [comment]
With #69, this issue can probably be closed. The up-to-date cheatsheets and handouts are now shown in the README, and are available at https://matplotlib.org/cheatsheets/.
