### ISSUE TITLE
Has GitHub Pages been activated for this repo?

### ISSUE THREAD

**Issue by jimustafa** [matplotlib/cheatsheets#66]
The cheatsheets that are automatically built should be available [here](https://matplotlib.github.io/cheatsheets/cheatsheets.pdf), but I am getting a `404`. If GH Pages has not been activated for the repo, that could be the cause. There may also be a problem with the project pages and having a custom domain for the organization pages, as discussed in isaacs/github#547.

**Comment by rougier** [comment]
In the page setup, it's written "Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS (matplotlib.org) — Troubleshooting custom domains

HTTPS provides a layer of encryption that prevents others from snooping on or tampering with traffic to your site.
When HTTPS is enforced, your site will only be served over HTTPS. Learn more. "

The address is thus http://matplotlib.github.io/cheatsheets/ but I'm unable to access it (http is replaced by https)

**Comment by jimustafa** [comment]
Maybe @QuLogic or @tacaswell would have some insight into this, given their work on the [matplotlib docs repo](https://github.com/matplotlib/matplotlib.github.com). It seems that if GH Pages is configured properly for this repo, then they should be available at https://matplotlib.com/cheatsheets/.

**Comment by jimustafa** [comment]
Not sure what changed, but things seem to be working now; see [here](https://matplotlib.org/cheatsheets/cheatsheets.pdf) as an example.

**Comment by tacaswell** [comment]
The matplotlib.github.io is still broken for me, but the matplotlib.org one does work.  The linked issue seems plausible but I read to `CNAME` and do not have the bandwidth to dig into that today!

The reason https://matplotlib.org/cheatsheets/ does not work is that there is no index.html in https://github.com/matplotlib/cheatsheets/tree/gh-pages so there is nothing to serve (whereas if the url goes all they way to the pdf in works).  I think adding a basic landing page would be very helpful.
